# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'

target 'luxalog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for luxalog

  target 'luxalogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'luxalogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
